### ISSUE TITLE
DeviceAggregation - Device hierarchy can boil down to single table

### ISSUE THREAD

**Issue by bwilk** [ismop/dap#10]
Idea:

Device is generic type that can represent parent - child hierarchy. It has its type, set of parameters and set of static metadata - stored in specialized table. Eg. Device of type - neosentio_sensor has single parameter, identifier of parent probe, and a set of metadata stored in table Noesentio Sensor.

Maybe Node instead of Device wuold be a better name. 

Serializer returns metadata together with generic node data.

**Comment by nowakowski** [comment]
@bwilk So you would propose to replace `DeviceAggregation` with just another `Device` which has a parent/child link with the `Device` objects representing aggregation components? If so, I rather like the idea.

**Comment by nowakowski** [comment]
Closing this for now since there is no support for this idea in the Project consortium.
