### ISSUE TITLE
Improve parameter naming for water level sensors

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#118]
Take a look at the legend in the following snapshot:

![screenshot from 2016-07-04 09 28 38](https://cloud.githubusercontent.com/assets/1506876/16553601/d0fa7e18-41c9-11e6-91c2-b0bdb3d514cf.png)

**Comment by dharezlak** [comment]
Proposal:

* pump_monitoring dla PV-> Poziom wody - czujnik 1
* pump_monitoring dla 1_PV-> Poziom wody - czujnik 2
* pump_monitoring dla 2_PV-> Poziom wody - średnia dla czujników 1 i 2
* pump_monitoring dla SP-> Poziom wody - wartość zadana

**Comment by nowakowski** [comment]
Done as requested.

**Comment by dharezlak** [comment]
* `czujnik 1` is repeated for two of the water level parameters

**Comment by nowakowski** [comment]
@dharezlak There's only one `Parameter` in the database with `parameter_name` set to `czujnik 1`. Could you post a screenshot?

**Comment by dharezlak** [comment]
I can post two:

![screenshot from 2016-07-12 16 48 10](https://cloud.githubusercontent.com/assets/1506876/16771477/ee39cbea-4850-11e6-8af6-59316568ec13.png)

![screenshot from 2016-07-12 16 50 52](https://cloud.githubusercontent.com/assets/1506876/16771476/ee37da9c-4850-11e6-9260-26163e10afbf.png)

**Comment by nowakowski** [comment]
Okay, I see - they're both part of the same Device. I can rename one (or both) but can you suggest appropriate names?

**Comment by nowakowski** [comment]
Okay; fixed.
