### ISSUE TITLE
Data exported to CSV is repeated 4 times

### ISSUE THREAD

**Issue by balis** [ismop/dap#120]
Reportedly any readings exported from GUI to CSV are repeated 4 times and are ordered randomly.

**Comment by mkasztelnik** [comment]
I don't believe that is should be assigned to me. From the UI perspective only user request is redirected to DAP.

**Comment by nowakowski** [comment]
This is probably due to the presence of multiple copies of the same reading in DAP (as reported by MOM). @bwilk - as the author of the export service, could you run `.uniq` on the result sets to avoid this issue?

**Comment by nowakowski** [comment]
@bwilk - this is now urgent (cf. MB's message of 18 July). Could you follow up on this issue before the meeting on Wed?

**Comment by bwilk** [comment]
Implemented and tested in https://github.com/ismop/dap/commit/383d287863c7b3e11e6cacf6adb14a1e41ebe687
