### ISSUE TITLE
Introduce API for scenario data retrieval

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#13]
Query based on threat assessment id. DAP should:
* Based on timeline ids in the request query correlate column names with measurement types of parameters,
* Based on the found index and threat assessment start date approximate timestamps for each row in the scenario,
* Limit the returned parameters only for measured equivalents (real world values).

**Comment by nowakowski** [comment]
@dharezlak Could you tell us whether this is still relevant?

**Comment by dharezlak** [comment]
I suppose it is no more relevant since approach to handle scenario data has been reworked.
