### ISSUE TITLE
Implement changes in Scenario model

### ISSUE THREAD

**Issue by nowakowski** [ismop/dap#130]
- Add a field named `threat_level` (int)
- Add `scenarios.name`, `scenarios.description` and `scenarios.threat_level` to `ThreatLevelController` output
- Remove TB's obsolete calculator service
- Fix specs etc.

**Comment by mpawlik** [comment]
+1 for this issue, sorry for not posting this by myself.

**Comment by nowakowski** [comment]
@mpawlik @mkasztelnik Deployed to dap-dev. Please check whether everything works fine on your end.

**Comment by nowakowski** [comment]
Still on hold until we figure out what to do with existing records (cf. #133)
