### ISSUE TITLE
Profile levee_id is not id but something more

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#132]
According to DAP documentation `Profile#levee_id` returned by REST API should be: "identifier of the levee the profile belongs to". It is something more. Take a look at sample result:

```
"levee_id":{
  "id":1,"name":"Obwałowanie eksperymentalne - Czernichów",
  "emergency_level":"none",
  "threat_level":"none",
  "threat_level_updated_at":"2016-05-30T09:25:20.229Z",
  "base_height":211.0
}
```

Most probably it was made for same reason - @nowakowski, @dharezlak do you know the story behind it? In eitwid I don't see any mapping between this field and [POJO](https://github.com/ismop/eitwid/blob/development/src/main/java/pl/ismop/web/client/dap/profile/Profile.java)

It propose to:
- if needed update documentation, otherwise `levee_id` should return only levee id
- if these values are required rename `levee_id` into something more meaningful (e.g. `levee`)

**Comment by mkasztelnik** [comment]
This can be a cause of #131

**Comment by nowakowski** [comment]
You're right; the entire `levee` object is serialized instead of just the ID. Might have been done on purpose. ;) If I change this to return the ID, will it break the UI?

**Comment by mkasztelnik** [comment]
Most probably no since this field is not serialized by pojo I linked, but I'm not sure if it is not used by "porownywaczka" - @mpawlik, @tbartynski  can you check it?

**Comment by mkasztelnik** [comment]
I browsed profile serializer history and this change is made by @bwilk in ddea3b29a9431a17e313c37a617d0ecf75f2845f. @bwilk do you remember why this change was introduced?

**Comment by nowakowski** [comment]
Ping @bwilk

**Comment by tbartynski** [comment]
Porównywaczka does not use levees so it won't be affected.

**Comment by nowakowski** [comment]
Ping @bwilk (again).

**Comment by dharezlak** [comment]
Just spotted this again. @bwilk: are you reading these notifications? Looks like this issue could be quickly fixed but we need your input!

**Comment by bwilk** [comment]
Hey guys - I read these notifications very rarely. E.g. for now I have 74 unread notifications - most of them does not concern discussions I'm involved in. Sorry guys, but I suppose you all know where to find me... As for the only question which has been addressed to me in this discussion - no, I don't remember. What is the problem we are working on in this thread? I simply don't understand this without a word of further explanation - I reckon everybody except me probably know this problem very well, but forgive me - I don't.

**Comment by bwilk** [comment]
https://github.com/ismop/dap/pull/172

**Comment by bwilk** [comment]
There is nothing more I can say about it - does it satisfy the issuer?
