### ISSUE TITLE
Why threat_levels REST API has many threat_assesments?

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#135]
This is just to remember my question to @tbartynski next week: why `/threat_levels` `ThreatLevel` element has many `threat_assessments` which have many `scenarios`? 

As far as I understand purpose of the `/threat_levels` rest interface is to return last threat levels (in the future for given time or current time when date is not set) with scenarios ranking for all profiles. If I'm right than why this rest interface cannot be simplified into something like:

```json
{
  "threat_levels": [ {
        "profile_id": 3923,
        "date": "2016-07-11T08:02:24.449Z",
        "threat_level": "2  this would be nice, but I can calculate it in UI using scenarios list",
        "scenarios": [ {
          "similarity": 0.8,
          "threat_level": 2,
          "scenario_id": 2057,
          "name": "Scenario no. 1",
          "description": "Sample scenario"
        }, {
          "similarity": 0.4,
          "threat_level": 1,
          "scenario_id": 2058,
          "name": "Scenario no. 2",
          "description": "Another sample scenario"
        } ],
   }, {
      ....
  }]
}
```

**Comment by dharezlak** [comment]
From what I remember the purpose of `threat_level_assessment_runs` is to indicate whether there are any assessments running at a given time. This is to be able to show full assessment info in the UI with just one request.

I guess the additional `threat_assessments` object is there to describe what is inside the following array.

I am not sure what the ellipsis in the above structure means? Is it replacing the `threat_level_assessment_runs` part?

**Comment by mkasztelnik** [comment]
No the `threat_level_assessment_runs` stays as it is. I was not referring to this element at all. The only part which is not clear for me is why there is additional 1-n relation between `threat_levels` and `threat_assessments`. It is possible to have more than one `threat_assessments` returned in this rest api? If yes than how to interpret it?

**Comment by dharezlak** [comment]
OK, this part was obvious so I did not see it. Simply, there can be many runs of the similarity computation engine (aka "porównywaczka"). The number of results, as documented, can be limited by the `limit` parameter if a smaller number is needed. The UI can limit this to only one but it can also show more.

**Comment by mkasztelnik** [comment]
Ok this explains a lot. I thought that `limit` is connected with number of returned scenarios in the ranking.
