### ISSUE TITLE
REST api doesn't allow for creating threat_assessment->threat_assessment_run relations

### ISSUE THREAD

**Issue by mpawlik** [ismop/dap#136]
Creating threat_asessment with threat_assessment_run_id parameter doesn't cause the threat_assessment_run_id value to show up, when later retrieving threat_assessment entity.

It seems that ThreatAssessmentsController::create is missing some functionality (something similar to profile_ids handling).

**Comment by nowakowski** [comment]
Controller had wrong list of permitted params. @mpawlik - could you try it now on dev? (I deployed a fix.)

**Comment by mpawlik** [comment]
Looks like it's working.
