### ISSUE TITLE
Add `from`, `to` into `/threat_levels` REST API

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#137]
This is needed to get threat levels for given experiment time.

**Comment by mkasztelnik** [comment]
Any news when it can be implemented?

**Comment by tbartynski** [comment]
I can go back to this issue next Monday. We can discuss whether this issue of #139 is more important.

**Comment by mkasztelnik** [comment]
Both has the same importance level, because both are required by new feature implemented by me in eitwit

**Comment by tbartynski** [comment]
Then pick one you want me to work on Monday.

**Comment by mkasztelnik** [comment]
I propose following schema for `/threat_levels` query params:

```
threat_levels?limit={limit}&from={from}&to={to}&status={status}
```
