### ISSUE TITLE
Add filtering by threat assessment run status

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#139]
On experiment view I'm interested only about finished threat assessments from given time interval, thus adding `status` query param is important.

**Comment by mkasztelnik** [comment]
Any news when it can be implemented?

**Comment by tbartynski** [comment]
I can go back to this issue next Monday.

**Comment by mkasztelnik** [comment]
I propose following schema for `/threat_levels` query params:

```
threat_levels?limit={limit}&from={from}&to={to}&status={status}
```

**Comment by mkasztelnik** [comment]
After discussion with @tbartynski we agreed that status is not needed for my case, since `ThreatAssesment` section contains alreasy finished calculations.
