### ISSUE TITLE
Enable DAP to store threat assessment state

### ISSUE THREAD

**Issue by tbartynski** [ismop/dap#140]
Extend the model with _state_ enum field with _running_, _finished_ and _error_ values.
Add a REST method to update the _state_ of ThreatAssessment record.
Perhaps adding a validation that a Result is associated with Scenario would also be useful?

**Comment by nowakowski** [comment]
Deployed to dap-dev. Use PUT threat_assessments/#{id} to update the new `status` field (default is `running`).
