### ISSUE TITLE
Not all neosentio sensors assigned to profile

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#148]
Take a look at attached screenshot:

![not_assigned_sensors](https://cloud.githubusercontent.com/assets/1265430/17846308/12bda63c-6848-11e6-942b-9a4220208de1.png)

**Comment by nowakowski** [comment]
@mkasztelnik I reassigned the offending profile to section 8 (the straight section). Hopefully this artifact should be gone now. Please close this ticket if you like the results.

**Comment by nowakowski** [comment]
![sec8](https://cloud.githubusercontent.com/assets/4568385/17943465/cea28314-6a3b-11e6-8670-23273e3a55e4.png)

**Comment by nowakowski** [comment]
Done on dev and on prod.
