### ISSUE TITLE
Profile with id 141 on prod has wrong coordinates

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#149]
`[19.676602,49.980666],[19.676602,49.980666]`: the second coordinate is repeated.

**Comment by dharezlak** [comment]
The same thing can be spotted on the development environment.

**Comment by mkasztelnik** [comment]
Do you know how coordinates should looks like? Than I should be able to correct it.

**Comment by mkasztelnik** [comment]
Right now it looks as follow in dap: `LINESTRING (19.676602 49.980666, 19.676602 49.980666)`

**Comment by dharezlak** [comment]
Could you try the following: [19.676550933948498,49.980666],[19.6768449865425,49.980666]?

**Comment by dharezlak** [comment]
After all it is the first coordinate which is wrong.

**Comment by mkasztelnik** [comment]
Done as requested on dev and prod
