### ISSUE TITLE
Wrong profile-section association

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#171]
On the development instance profile with id `7` is associated with section with id 7. The profile does not have any shape so it looks like it is bogus one. Please, do apprehend and incinerate.

**Comment by dharezlak** [comment]
Also, check if this is occurring on production.

**Comment by dharezlak** [comment]
Other profile ids with `null` shape to be checked: `3`, `1`, `6`. Just to be sure filter all the profiles to check for those with a `null` shape.

**Comment by nowakowski** [comment]
@dharezlak Old issue and I believe it does not occur on production. I fixed it once - but only on prod, because (i) it involved a lot of manual calculations; (ii) I thought it wouldn't matter that the assignments are incorrect on dev. Do you want me to fix dev regardless?

**Comment by nowakowski** [comment]
On further inspection, all those profiles aggregate old (deprecated) FO devices. They should never be visualized in any case. Could you perhaps just ignore them in the GUI?

**Comment by dharezlak** [comment]
It looks like these profiles are also present in DAP production instance so removing them is now essential. From the UI perspective it should suffice to remove the section association (remove the section_id value). As for ignoring them, the UI already does that when drawing profiles. The problem is with UI logic which traverses the levee structure to select all budokop/neosentio devices for a section.

**Comment by nowakowski** [comment]
@dharezlak I've followed your recommendation and removed the `section` assignment for all offending profiles. If you feel this is good enough - please close this ticket; otherwise complain. ;)

**Comment by dharezlak** [comment]
This is good enough. Now, it's time for #167 which is another blocker for UI's new feature :)
