### ISSUE TITLE
Wrong coordinates of one of the sections

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#18]
In MultiPoint geometry first and last points should be identical. For section with id=8 it is not the case. Please correct.
![screenshot from 2015-09-11 12 12 01](https://cloud.githubusercontent.com/assets/1506876/9812554/6c6ed1c2-587e-11e5-8325-8dcdc6f1a066.png)

**Comment by nowakowski** [comment]
Temporarily fixed on prod. Will be permanently fixed once I receive new Budokop sensor data.
