### ISSUE TITLE
Indicate whether a profile is a Budokop or NeoSentio one directly in the returned profile json

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#19]
This will greatly improve the UI's metadata popup panel

**Comment by mkasztelnik** [comment]
@nowakowski any deadline for this issue? We need it to implement https://github.com/ismop/eitwid/issues/44

**Comment by nowakowski** [comment]
@mkasztelnik Technically there is nothing difficult about this; however the question belies the logic of our data model. A profile is a **generic** entity that is not specific to a device manufacturer, i.e. DAP allows a profile to contain devices which are contributed by various manufacturers. In order to implement this feature I need you (or @dharezlak) to tell me how DAP should determine that a given profile is, in fact, a "budokop profile" (or a "neosentio profile").

**Comment by mkasztelnik** [comment]
The answer is simple - current profiles are a budokop profiles, new one created when neosentio sensors will be registered will be neosentio profiles :smile:

**Comment by nowakowski** [comment]
It is dangerous to assume that any new profile inserted into DAP must be a "neosentio profile". As a person who's very conscious about software development practices surely you must be aware of this. ^_^

**Comment by mkasztelnik** [comment]
I'm not saying that you need to hardcode this assumption in the code :) I'm saying that in ismop installation existing profiles are budokop new one will be neosentio.

**Comment by nowakowski** [comment]
OK, so what you want is a new field in the `Profile` model with an enum data type (currently restricted to `:neosentio` and `:budokop`), right?

**Comment by mkasztelnik** [comment]
I want REST interface to return neosentio or budokop in one of Profile attribute - it depends on you how it will be implemented in DAP.

**Comment by nowakowski** [comment]
Okay.

**Comment by nowakowski** [comment]
@dharezlak @mkasztelnik Done and deployed to dap-dev. The new field is named `Profile.vendor` and serialized accordingly in `GET /profiles`. Value is set to `budokop` for all existing profiles. Before I merge this into master and deploy to prod I will need you to confirm that this is what you wanted.

**Comment by mkasztelnik** [comment]
I looks ok.

**Comment by nowakowski** [comment]
Replaced `vendor` with `vendors` (list type).

**Comment by nowakowski** [comment]
Done. Deployment held back by https://github.com/ismop/eitwid/issues/44 (pending @dharezlak 's approval).
