### ISSUE TITLE
Introduce an experiment entity into DAP data hierarchy

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#20]
It should store experiment start date and a wave shape (the wave shape will come from the modelling team as discussed in the meeting).

**Comment by nowakowski** [comment]
@dharezlak Can you determine what datatype should be assigned to the wave shape?

**Comment by dharezlak** [comment]
Well, I guess even a concatenated string would do. However, in the REST layer I would prefer a hash of timestamps as keys and heights as values.

**Comment by mpawlik** [comment]
I suppose the "float" datatype would be good for storing waves ;)

**Comment by dharezlak** [comment]
Fields:
* startDate,
* endDate,
* id,
* name,
* description,
* timelines.

**Comment by dharezlak** [comment]
Experiment entity should also hold a field with levee id.
