### ISSUE TITLE
Some fibre devices are not assigned to any section

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#34]
Some of registered fibre devices are not assigned to any section. Bellow you can find the one I found:

```
Device sw184 is not assigned to any section
Device sw185 is not assigned to any section
Device sw186 is not assigned to any section
Device sw187 is not assigned to any section
Device sw188 is not assigned to any section
```

**Comment by nowakowski** [comment]
@mkasztelnik Those are the devices which "protrude" from the levee on @mpawlik 's map - their geographical location is not contained within the bounding box of any levee section, hence the nil assignment.

**Comment by mkasztelnik** [comment]
Ok so the problem is connected with imported data not with dap - closing
