### ISSUE TITLE
Measurement is represented in DB by multiple record

### ISSUE THREAD

**Issue by tbartynski** [ismop/dap#42]
GET /api/v1/measurements?timeline_id=52&time_from=2015-10-03%209:40:40%20+0200&time_to=2015-10-03%209:45:40%20+0200
returns
{"measurements":[{"id":7682653,"value":0.0270000007003546,"timestamp":"2015-10-03T07:45:23.000Z","source_address":null,"timeline_id":52},{"id":7681565,"value":0.0270000007003546,"timestamp":"2015-10-03T07:45:23.000Z","source_address":null,"timeline_id":52},{"id":7680477,"value":0.0270000007003546,"timestamp":"2015-10-03T07:45:23.000Z","source_address":null,"timeline_id":52}]}

One can notice that for a single measurement (value and timestamp) 3 records are returned.

**Comment by bwilk** [comment]
Tested in production. It seems to be fixed by the way. Please reopen if encountered again
