### ISSUE TITLE
Relation between ThreatAssessments and ThreatAssessmentRuns

### ISSUE THREAD

**Issue by nowakowski** [ismop/dap#58]
@tbartynski @mkasztelnik The note I received from @tbartynski appears to claim that a `ThreatAssessmentRun` should have many `ThreatAssessments`. This is evident from the fact that you are asking for a `threat_assessment_run_id` field in `ThreatAssessments`, and also the `1` and `n` annotations next to `ThreatAssessmentRun` and `ThreatAssessment` entities respectively.

Are you sure this is correct? Shouldn't it be the other way around (i.e. many `ThreatAssessmentRuns` for a single `ThreatAssessment`)?

**Comment by tbartynski** [comment]
This is correct. TAR has many TAs.
