### ISSUE TITLE
The type of the ground, a section is constructed from, should be stored in DAP 

### ISSUE THREAD

**Issue by bwilk** [ismop/dap#6]
There are to altrernative solutions:
1. String value - section_type in the Section entity 
2. Table { id, human-readable-name, k-parameter, other metadata ... }

REST endpoint for Section should aggregate all of the information concerning type of the ground. 

@dharezlak @nowakowski

**Comment by dharezlak** [comment]
@bwilk: Is the colour value going to be there in DAP as well?
