### ISSUE TITLE
Add section metadata

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#68]
During UI presentation we were asked to add section colors and sections metadata. In the attachment you can find pdf with colors and needed metadata.

These information should be accessible though REST API.

[parametry_gruntow.pdf](https://github.com/ismop/dap/files/29343/parametry_gruntow.pdf)

\cc @dharezlak

**Comment by mkasztelnik** [comment]
@nowakowski any deadline for this issue? We need it to implement https://github.com/ismop/eitwid/issues/42.

**Comment by nowakowski** [comment]
I can get this done by tomorrow.

**Comment by nowakowski** [comment]
@mkasztelnik Created a new model named `SoilType`. Each Section now belongs to a SoilType. Populated the DB with data derived from the PDF and manually assigned each Section to the correct SoilType on dap-dev. Values are serialized directly in `GET /sections` (i.e. there's no separate API for querying SoilTypes - I can create one if you want, but it seems unnecessary). Before I merge this into master and deploy to prod I will need you to confirm that this is what you wanted.

**Comment by mkasztelnik** [comment]
Would it be possible to insert this information into `/sections` response similar like for device metadata?

**Comment by nowakowski** [comment]
@mkasztelnik It's already happening.

**Comment by mkasztelnik** [comment]
I see :+1:

**Comment by nowakowski** [comment]
:)

**Comment by nowakowski** [comment]
Done. Deployment held back by https://github.com/ismop/eitwid/issues/44 (pending @dharezlak 's approval).
