### ISSUE TITLE
Set weather station parameter names the same way as in production

### ISSUE THREAD

**Issue by dharezlak** [ismop/dap#80]
Recently modifications were made to production weather parameters. Apply the same changes to development counterparts.

**Comment by dharezlak** [comment]
This got quite urgent as it prevented spotting a bug before doing a release to production.

**Comment by dharezlak** [comment]
To make it clear weather station parameter names were changes (e.g. from `Stacja KI - wilgotność powietrza` to `Wilgotność powietrza`).

**Comment by nowakowski** [comment]
Currently rebuilding dap-dev database and populating it with production data. This might take a while (30 minutes or so) and dap-dev will not work during that time. Bear with us.

**Comment by nowakowski** [comment]
dap-dev rebuilt and repopulated with production data (including WS parameter names). @dharezlak please close this task if you believe your issue has been resolved.

**Comment by nowakowski** [comment]
@dharezlak Can we close this?

**Comment by bwilk** [comment]
I think we can
