### ISSUE TITLE
Null is returned in device_aggregation vendors list

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#81]
Take a look at response from this url: https://dap-dev.moc.ismop.edu.pl/api/v1/device_aggregations/52

```json
vendors: [
"budokop",
null
]
```

`null` should not exist there.

**Comment by nowakowski** [comment]
Fixed in #82 and deployed to dap-dev. Sorry.

**Comment by nowakowski** [comment]
Deployed to dap-prod.
