### ISSUE TITLE
Measurement table trigger violates CHECK constraint in child tables

### ISSUE THREAD

**Issue by nowakowski** [ismop/dap#94]
Due to DATETIME conversion mechanics the trigger does not correctly handle measurements which occur in the first hour following CT switchover (i.e. the first hour of each month - e.g. 2016-03-01 00:30:00). Observed by @mkasztelnik on dap-dev

**Comment by nowakowski** [comment]
Fixed in latest iteration of #85 (commit f31d9dd).

**Comment by nowakowski** [comment]
@bwilk I had to repartition the `measurements` table. Could you check that flume-dev still works correctly (i.e. inserts records into `measurements` on dap-dev)?

**Comment by bwilk** [comment]
for me it looks OK - measurements are stored correctly

**Comment by bwilk** [comment]
@nowakowski can this issue be closed?
